            - name: Wails Build Action
  # You may pin to the exact commit or the version.
  # uses: Snider/build@d0b7d7500f3344ebed78d1a59e3f183977d62d1f
  uses: Snider/build@v2.2
  with:
    # Platform to build for
    build: # optional, default is true
    # Sign the build
    sign: # optional, default is false
    # Uploads workflow & uploads tag builds to a release
    package: # optional, default is true
    # Build a Windows Installer
    nsis: # optional, default is true
    # The name of the binary file
    build-name: chameleon
    # Platform to build for
    build-platform: darwin/universal, windows/amd64 # optional, default is darwin/universal
    # Wails version to use
    wails-version: # optional, default is latest
    # Webview2 installer method [download,embed,browser,error]
    wails-build-webview2: # optional, default is download
    # Version of Go to use
    go-version: # optional, default is ^1.18
    # Node js version
    node-version: # optional, default is 16.x
    # This gets run into bash, use the full command
    deno-build: # optional, default is 
    # This gets run into bash, use the full command
    app-working-directory: # optional, default is .
    # This gets run into bash, use the full command
    deno-working-directory: # optional, default is .
    # Deno version to use
    deno-version: # optional, default is v1.20.x
    # MacOS Application Certificate id
    sign-macos-app-id: # optional, default is 
    # MacOS Apple password
    sign-macos-apple-password: # optional, default is 
    # MacOS Application Certificate
    sign-macos-app-cert: # optional, default is 
    # MacOS Application Certificate Password
    sign-macos-app-cert-password: # optional, default is 
    # MacOS Installer Certificate id
    sign-macos-installer-id: # optional, default is 
    # MacOS Installer Certificate
    sign-macos-installer-cert: # optional, default is 
    # MacOS Installer Certificate Password
    sign-macos-installer-cert-password: # optional, default is 
    # Windows Signing Certificate
    sign-windows-cert: # optional, default is 
    # Windows Signing Certificate Password
    sign-windows-cert-password: # optional, default is 
          
